trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    arguments: '-c Release'
  displayName: Compile
  
- pwsh: |
    docker compose up -d
  workingDirectory: test/hello-sqlserver
  displayName: Start SQL Server

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    arguments: '-c Release --no-build'
  displayName: Run Unit Tests

- task: Docker@2
  inputs:
    command: 'build'
    Dockerfile: 'Container.Dockerfile'

- pwsh: |
    new-item publish/container -itemtype directory -force
    docker save -o publish/container/azure-workshop.tar $(Build.BuildId)
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: 'publish/container'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/azure-workshop.zip'
    replaceExistingArchive: true

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)'
    artifact: 'azure-workshop'
    publishLocation: 'pipeline'
